package main

// DO NOT EDIT, this file is generated by hover at compile-time for the shutdown_platform plugin.

import (
	flutter "github.com/go-flutter-desktop/go-flutter"
	shutdown_platform "github.com/BestBurning/shutdown_platform/go"
)

func init() {
	// Only the init function can be tweaked by plugin maker.
	options = append(options, flutter.AddPlugin(&shutdown_platform.ShutdownPlatformPlugin{}))
}
